use kube::CustomResource;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// Struct corresponding to the Specification (`spec`) part of the `Echo` resource, directly
/// reflects context of the `echoes.example.com.yaml` file to be found in this repository.
/// The `Echo` struct will be generated by the `CustomResource` derive macro.
#[derive(CustomResource, Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
#[kube(
    group = "cnad.nl",
    version = "v1beta1",
    kind = "CDBootstrap",
    plural = "cdbootstraps",
    derive = "PartialEq",
    namespaced
)]
#[kube(status = "CDBootstrapStatus")]
pub struct CDBootstrapSpec {
    pub replicas: i32,
}

#[derive(Deserialize, Serialize, Clone, Debug, PartialEq, Default, JsonSchema)]
pub struct CDBootstrapStatus {
    pub reconcile_success: bool,
}